function guessTheNumber(start, end) {
  var userName = prompt("Enter username"); console.log(`Hi ${userName} \n Welcome to guess the number. \nINSTRUCTIONS;                                            Pick a random number between the range 1 and 2. If your guess matches the numerry randomly generated by the game you move to the next level and the range of selection increases by 1, if not its game over. Goodluck!`);
  var start = 1,
    end = 2,
    point = 0,
    result = true,
    level = 1;
  while (result) {
    var random = Math.floor(Math.random() * start + end);
    var guess = Number(prompt("Guess the number"));
    if (guess === random) {
      point++;
      end++;
      level++;
      console.log(`Congratulations move to the next level ${level}`);
      result = true;
    } else console.log(`Oops Game over you finished with ${point} points`);
    var resolution = Number(prompt('would you like to continue or leave game \n Enter 1 to continue and 2 to leave game  '));
    if (resolution = 1) { post = true; }
    else { post = false }
  }

}
guessTheNumber(1, 2);